"""Minimum-viable plaintext digest renderer for Day 6.

Produces a simple "Doceree CI Daily Digest - YYYY-MM-DD" plaintext body
grouped by competitor, with each finding showing severity badge, title,
summary, and URL. Day 11 replaces this with the full HTML template (with
dark mode, mobile-perfect rendering, etc.). For Day 6 we just need
deliverable text so we can verify Gmail send works end-to-end.
"""
from __future__ import annotations

from collections import defaultdict
from datetime import datetime, timezone
from zoneinfo import ZoneInfo

from jinja2 import Environment, StrictUndefined

from schema.finding import Finding

_IST = ZoneInfo("Asia/Kolkata")


_PLAINTEXT_TEMPLATE = """\
Doceree CI - Daily Competitive-Intelligence Digest
{{ run_date }} | {{ findings | length }} findings across {{ competitor_count }} competitors

{%- if findings %}
{%- for competitor, items in by_competitor.items() %}

== {{ competitor }} ({{ items | length }}) ==
{%- for f in items %}

  [Sev {{ f.effective_severity }} / Conf {{ f.effective_confidence }}] {{ f.title }}
  {{ f.summary }}
  Evidence: "{{ f.evidence_quote | truncate(200) }}"
  Signal: {{ f.signal_type }}{% if f.products %} | Products: {{ f.products | join(', ') }}{% endif %}
  URL: {{ f.url }}
{%- endfor %}
{%- endfor %}
{%- else %}

No material updates today. (Pipeline ran successfully but produced no findings.)
{%- endif %}

--
Generated by doceree-ci at {{ generated_at_ist }} IST
"""


def _build_env() -> Environment:
    """Build a Jinja2 environment with strict undefined access so missing
    template variables raise loudly rather than silently rendering empty."""
    return Environment(
        autoescape=False,  # plaintext output - no HTML escaping
        keep_trailing_newline=True,
        undefined=StrictUndefined,
    )


def render_plaintext(
    findings: list[Finding],
    *,
    run_date: str | None = None,
) -> str:
    """Render a plaintext daily digest.

    Args:
        findings: All findings included in today's digest. Already filtered
                  to the day's run cohort (T7-input).
        run_date: ISO-8601 date string (YYYY-MM-DD) shown in the header.
                  Defaults to today in IST.

    Returns:
        Plaintext string ready for `gmail.send_message(plaintext=...)`.
    """
    now_ist = datetime.now(timezone.utc).astimezone(_IST)
    run_date = run_date or now_ist.date().isoformat()

    by_competitor: dict[str, list[Finding]] = defaultdict(list)
    for f in findings:
        by_competitor[f.competitor].append(f)
    # Sort by severity desc within each competitor
    for items in by_competitor.values():
        items.sort(key=lambda x: -x.effective_severity)
    # Sort competitor groups by their max severity desc, then by name
    sorted_competitors = sorted(
        by_competitor.items(),
        key=lambda kv: (-max((f.effective_severity for f in kv[1]), default=0), kv[0]),
    )

    env = _build_env()
    template = env.from_string(_PLAINTEXT_TEMPLATE)
    return template.render(
        findings=findings,
        by_competitor=dict(sorted_competitors),
        competitor_count=len(by_competitor),
        run_date=run_date,
        generated_at_ist=now_ist.strftime("%Y-%m-%d %H:%M"),
    )


def render_subject(findings: list[Finding], *, run_date: str | None = None) -> str:
    """Build the email subject line.

    Format: "Doceree CI - YYYY-MM-DD - N findings (S sev-5+)" so Sherry can
    triage from the subject alone without opening.
    """
    now_ist = datetime.now(timezone.utc).astimezone(_IST)
    run_date = run_date or now_ist.date().isoformat()
    n = len(findings)
    n_sev5 = sum(1 for f in findings if f.effective_severity == 5)
    n_sev4plus = sum(1 for f in findings if f.effective_severity >= 4)
    if n == 0:
        return f"Doceree CI - {run_date} - no findings"
    flag = ""
    if n_sev5 > 0:
        flag = f" - {n_sev5} URGENT"
    elif n_sev4plus > 0:
        flag = f" - {n_sev4plus} sev-4+"
    return f"Doceree CI - {run_date} - {n} findings{flag}"
