"""LLM-fillable response schemas for each pipeline stage.

Each schema is the `response_schema` for one Gemini call. Keeping these
separate from the canonical `Finding` model lets us:
  - Use them as Gemini structured-output schemas without leaking pipeline-
    internal fields into the prompt context.
  - Apply provenance / lifecycle defaults deterministically in the
    pipeline rather than trusting the LLM to fill them.

Sprint 8 added two adversarial schemas (`AttributionCheck`,
`SeverityAdversarialCheck`) — outputs of the new T4a / T4b stages.
"""
from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field

ScoreLevel = Annotated[int, Field(ge=1, le=5)]


class FindingDraft(BaseModel):
    """LLM extract output. Promoted to a Finding by `pipeline.extract`."""

    model_config = ConfigDict(
        extra="forbid",
        str_strip_whitespace=True,
    )

    title: str = Field(min_length=1, max_length=500)
    summary: str = Field(min_length=10, max_length=4000)
    evidence_quote: str = Field(min_length=1, max_length=2000)
    signal_type: str = Field(min_length=1, max_length=64)
    products: list[str] = Field(default_factory=list, max_length=8)
    raw_severity: ScoreLevel
    raw_confidence: ScoreLevel


class FilterDecision(BaseModel):
    """LLM filter output. `keep=False` means the item is dropped from T2."""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)

    keep: bool
    reason: str = Field(min_length=1, max_length=64)


class AttributionCheck(BaseModel):
    """Stage 4a output. Flash answers: is the named competitor the SUBJECT
    of this article?

    `verdict='no'` causes the item to be dropped before extract. `unclear`
    passes through but lowers `attribution_confidence` on the resulting
    Finding so the renderer can surface uncertainty."""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)

    verdict: Literal["yes", "no", "unclear"]
    confidence: ScoreLevel
    reasoning: str = Field(min_length=1, max_length=200)


class SeverityAdversarialCheck(BaseModel):
    """Stage 4b output. Pro answers: does the evidence quote support the
    assigned severity?

    `verdict='rejected'` causes the Finding to be dropped from the digest.
    `demoted` keeps it but writes severity_after_check to the Finding.
    `kept` is the default green-light outcome."""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)

    verdict: Literal["kept", "demoted", "rejected"]
    severity_after_check: ScoreLevel
    confidence: ScoreLevel
    reasoning: str = Field(min_length=1, max_length=500)


class PerProductSynthesis(BaseModel):
    """T5 synth_per_product output. One paragraph per impacted Doceree
    product, generated by Pro from the day's findings + the product spec."""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)

    product_id: str = Field(
        min_length=1,
        max_length=64,
        pattern=r"^[a-z][a-z0-9_]*$",
    )
    impact_summary: str = Field(min_length=10, max_length=600)
    recommended_action: str = Field(min_length=1, max_length=200)


class StrategicSynthesis(BaseModel):
    """T6 synth_strategic output. Single cross-product narrative for the
    digest — what's the meta-pattern across today's findings, and what
    should the leadership team discuss next?"""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)

    pattern: str = Field(
        min_length=10,
        max_length=800,
        description="2-4 sentences identifying the cross-cutting pattern in "
                    "today's findings. Concrete and specific to today.",
    )
    implied_agenda: str = Field(
        min_length=10,
        max_length=400,
        description="1-2 sentences proposing the implied agenda item(s) for "
                    "the next product / leadership review.",
    )
